[package]
name = "project_odyssey"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

# Debug info seems to have quite a significant impact on linking times
[profile.dev-nodebug]
inherits = "dev"
debug = false
strip = "debuginfo"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
debug = false
panic = "abort"

[profile.release-wasm]
inherits = "release"
opt-level = 'z'
debug = false
strip = true

[dependencies]
bevy = "0.15.0"
bevy-inspector-egui = "0.28.0"
iyes_perf_ui = { git = "https://github.com/IyesGames/iyes_perf_ui", rev = "d8f3cbb2ec486b85a86b21e1aa32dcebd26ac884" }
leafwing-input-manager = { git = "https://github.com/Leafwing-Studios/leafwing-input-manager", rev = "d40715f2cf13aa3d3bcaa8fc5c33ed65c7abb8fd" }
petgraph = "0.6.5"
