# From https://www.mevlyshkin.com/blog/bevy-github-actions/#bevy-and-wasm
name: build

on:
  push:
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs: # here we are specifing all of the jobs
  build: # name of the job
    runs-on: ubuntu-latest # system, linux is the cheapest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      # Handle prereqs
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install linux dependencies
        run: sudo apt-get update; sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
      - name: Install wasm bindgen
        run: cargo install -f wasm-bindgen-cli

      # Handle build
      - name: Build wasm
        run: |
          cargo build --profile release-wasm --target wasm32-unknown-unknown
          wasm-bindgen --out-dir ./out/ --target web ./target/wasm32-unknown-unknown/release-wasm/project_odyssey.wasm
      - name: Optimize wasm for size
        uses: NiklasEi/wasm-opt-action@v2
        with:
          file: out/*.wasm

      # Handle deploy
      - name: Copy
        run: |
          cp -R assets out/
          cp wasm/index.html out/index.html
          touch out/.nojekyll
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          SQUASH_HISTORY: true
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: out # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
